function FreqVoltPlot(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 27-Jan-2016 11:42:53

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'Marker','diamond','LineWidth',2);

% Create xlabel
xlabel('Voltage (V)');

% Create ylabel
ylabel('Frequency (Hz)');

% Create title
title('Frequency vs Voltage');

box(axes1,'on');
