/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "GUI.h"
#include "main.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0             (GUI_ID_USER + 0x00)
#define ID_TEXT_0             	(GUI_ID_USER + 0x01)
#define ID_TEXT_1             	(GUI_ID_USER + 0x02)
#define ID_TEXT_2             	(GUI_ID_USER + 0x03)
#define ID_TEXT_3             	(GUI_ID_USER + 0x04)
#define ID_TEXT_4             	(GUI_ID_USER + 0x05)
#define ID_TEXT_5             	(GUI_ID_USER + 0x06)
#define ID_PROGBAR_0            (GUI_ID_USER + 0x07)
#define ID_TEXT_6             	(GUI_ID_USER + 0x08)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
///*********************************************************************
//WM global variables
WM_HWIN hDialog;
WM_HWIN hText_0;//Set Temperature
WM_HWIN hText_1;//setpoint
WM_HWIN hText_2;//°C
WM_HWIN hText_3;//Soldering Iron Temperature
WM_HWIN hText_4;//actual temp
WM_HWIN hText_5;//°C
WM_HWIN hText_6;//Heating power
WM_HWIN hProgbar_0;//progress bar
//
/*********************************************************************/
//user function prototypes
extern void StateMachine(void);
void Init_GUI(void);
//
// USER END
/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 320, 240, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_0, 0, 20, 140, 70, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_1, 0, 90, 140, 70, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_2, 140, 20, 140, 70, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_3, 280, 20, 40, 70, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_4, 140, 90, 140, 70, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_5, 280, 90, 40, 70, 0, 0x64, 0 },
  { PROGBAR_CreateIndirect, "", ID_PROGBAR_0, 10, 180, 300, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_6, 0, 210, 320, 30, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Set Tempere'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //TEXT_SetText(hItem, "Soldering\n Temperature");
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "Soldering Iron\r\n Temperature");
    //
    // Initialization of '340'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_D64);
    //TEXT_SetText(hItem, "340");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of °C
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetText(hItem,"°C");
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_32B_1);
    //
    // Initialization of '300'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, GUI_FONT_D64);
    //TEXT_SetText(hItem, "300");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_RED);//RED
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetText(hItem, "°C");
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_32B_1);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //TEXT_SetText(hItem, "Heating Power");
    // USER START (Optionally insert additional code for further widget initialization)
    // Initialization of 'Progressbar'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
    PROGBAR_SetText(hItem, "");
	PROGBAR_SKINFLEX_PROPS pProps;
	PROGBAR_GetSkinFlexProps(&pProps,0);
	pProps.aColorLowerL[0]=0x000029D4;//
	pProps.aColorLowerL[1]=0x001C33E2;//
	pProps.aColorUpperL[0]=0x00CDCDFF;//
	pProps.aColorUpperL[1]=0x009CACEE;//
	PROGBAR_SetSkinFlexProps(&pProps,0);
	//PROGBAR_SetValue(hItem, 60);
	//
    // USER END
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
/*********************************************************************/
void Init_GUI(void){
	  GUI_Init();//STemWin GUI initialization
	  WM_SetDesktopColor(GUI_BLACK);
	  GUI_SetBkColor(GUI_BLACK);
	  GUI_Clear();
	  hDialog=CreateWindow();
	  hText_0=WM_GetDialogItem(hDialog, ID_TEXT_0);
	  hText_1=WM_GetDialogItem(hDialog, ID_TEXT_1);
	  hText_2=WM_GetDialogItem(hDialog, ID_TEXT_2);
	  hText_3=WM_GetDialogItem(hDialog, ID_TEXT_3);
	  hText_4=WM_GetDialogItem(hDialog, ID_TEXT_4);
	  hText_5=WM_GetDialogItem(hDialog, ID_TEXT_5);
	  hText_6=WM_GetDialogItem(hDialog, ID_TEXT_6);
	  hProgbar_0=WM_GetDialogItem(hDialog, ID_PROGBAR_0);
	  WM_EnableMemdev(hDialog);//enabling memory devices
}
// USER END
/*************************** End of file ****************************/
