function h = buildGraphics

% In this function - 
% Callback, SelectionChangeFcn and SizeChangedFcn are used to perform 
% actions when a user interacts with the interface.

% Refer to the sub functions ResizeFigure, TogglePWM, LedToggleCallback for
% more information on how they are used to control inputs and outputs on
% the Arduino

% Create figure and button group
h.Figure = figure('MenuBar','None',...
    'NumberTitle','off',...
    'Name','Arduino Inputs and Outputs',...
    'SizeChangedFcn',@ResizeFigure);
setappdata(h.Figure,'oldposition',h.Figure.Position)
h.LedButtonGroup = uibuttongroup(...
    'Position',[0 0 1 1],...
    'SelectionChangeFcn', @(~,~) TogglePWM(h.Figure));
% Create titles for each component
h.Text1 = uicontrol('Style','text',...
    'Units','normalized',...
    'String','Button Position',...
    'Position',[0.1 0.8 0.35 0.1],...
    'HorizontalAlignment','center',...
    'FontSize',14);
h.Text2 = uicontrol('Style','text',...
    'Units','normalized',...
    'String','Control LED',...
    'Position',[0.55 0.8 0.35 0.1],...
    'HorizontalAlignment','center',...
    'FontSize',14);
h.Text3 = uicontrol('Style','text',...
    'Units','normalized',...
    'String','Potentiometer Voltage',...
    'Position',[0.1 0.35 0.35 0.1],...
    'HorizontalAlignment','center',...
    'FontSize',14);
h.Text4 = uicontrol('Style','text',...
    'Units','normalized',...
    'String','Play Tone',...
    'Position',[0.55 0.35 0.35 0.1],...
    'HorizontalAlignment','center',...
    'FontSize',14);
% Create components
h.ButtonPositionText = uicontrol('Style','text',...
    'Units','normalized',...
    'String','UP',...
    'Position',[0.15 0.6 0.25 0.1],...
    'HorizontalAlignment','center',...
    'FontSize',22);
h.PotentiometerVoltageText = uicontrol('Style','text',...
    'Units','normalized',...
    'String','0.00 V',...
    'Position',[0.1 0.2 0.25 0.1],...
    'HorizontalAlignment','right',...
    'FontSize',20);
h.PlayToneSlider = uicontrol('Style','slider',...
    'Units','normalized',...
    'BackgroundColor','white',...
    'Position',[0.55 0.2 0.35 0.08]);
h.LedSlider = uicontrol('Style','slider',...
    'Units','normalized',...
    'Position',[0.55 0.5 0.35 0.08],...
    'Max',5,...
    'BackgroundColor','white',...
    'Enable','off');
h.EnableLedToggle = uicontrol(h.LedButtonGroup,...
    'Style','radiobutton',...
    'String','On/Off',...
    'Tag','toggle',...
    'Units','normalized',...
    'Position',[0.55 0.7 0.15 0.1]);
h.EnableLedPwm = uicontrol(h.LedButtonGroup,...
    'Style','radiobutton',...
    'String','PWM Control',...
    'Tag','pwm',...
    'Units','normalized',...
    'Position',[0.55 0.6 0.35 0.1]);
h.LedToggle = uicontrol('Style','toggle',...
    'Units','normalized',...
    'String','OFF',...
    'Position',[0.7 0.7 0.2 0.1],...
    'Callback',@LedToggleCallback);

drawnow
setappdata(h.Figure,'handles',h)

function TogglePWM(f)
h = getappdata(f,'handles');
switch h.LedButtonGroup.SelectedObject.Tag
    case 'toggle'
        h.LedToggle.Enable = 'on';
        h.LedSlider.Enable = 'off';
    case 'pwm'
        h.LedSlider.Enable = 'on';
        h.LedToggle.Enable = 'off';
end

function LedToggleCallback(hToggle,~)
if hToggle.Value
    hToggle.String = 'On';
else
    hToggle.String = 'Off';
end

function ResizeFigure(f,~)
h = getappdata(f,'handles');

if ~isempty(h)
    oldpos = getappdata(f,'oldposition');
    newpos = f.Position;
    oldsize = sqrt(oldpos(3)^2+oldpos(4)^2);
    newsize = sqrt(newpos(3)^2+newpos(4)^2);
    scale = newsize/oldsize;
    
    h.Text1.FontSize = h.Text1.FontSize*scale;
    h.Text2.FontSize = h.Text2.FontSize*scale;
    h.Text3.FontSize = h.Text3.FontSize*scale;
    h.Text4.FontSize = h.Text4.FontSize*scale;
    h.EnableLedPwm.FontSize = h.EnableLedPwm.FontSize*scale;
    h.EnableLedToggle.FontSize = h.EnableLedToggle.FontSize*scale;
    h.PotentiometerVoltageText.FontSize = h.PotentiometerVoltageText.FontSize*scale;
    h.ButtonPositionText.FontSize = h.ButtonPositionText.FontSize*scale;
    h.LedToggle.FontSize = h.LedToggle.FontSize*scale;
    
    setappdata(f,'oldposition',newpos)
end